router_gmap/urls.py

from django.contrib import admin
from django.urls import path
from gmap.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', upload_file, name='upload'),
    path('',signin,name='login'),
    path('signup/',signup,name='signup'),
    path('home/',home, name='home'),
    path('map/',show_location,name='map'),
    path('leads/', show_leads, name='leads'),
    path("logout/",signout,name="logout"),
    path('profile/',profile, name='profile'),
    path('forgot/',forgot,name="forgot")
]

gmap/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
mapbox_access_token='pk.eyJ1Ijoic3J1dGh5c2l2YWRhcyIsImEiOiJjbHJ5dDRvbGYxb2ljMmtteHhpcDY3MmxxIn0.YN98-omLBLCwOKEyM4e5qA'

class UploadedFile(models.Model):
    
    file = models.FileField(upload_to='uploads/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.file.name
    
class profile(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username
    
class uploadedData(models.Model):
    
    column1_name = models.CharField(max_length=255, blank=True, null=True)
    column2_address = models.CharField(max_length=255, blank=True, null=True)
    column3_latitude=models.DecimalField(max_digits=9, decimal_places=6,null=True)
    column4_longitude= models.DecimalField(max_digits=9, decimal_places=6,null=True)
    column5_city = models.CharField(max_length=255, blank=True, null=True)
    column6_district = models.CharField(max_length=255, blank=True, null=True)
    column7_state = models.CharField(max_length=255, blank=True, null=True)
    column8_country = models.CharField(max_length=255, blank=True, null=True)
    column9_zipcode = models.CharField(max_length=20)
    column10_email=  models.EmailField()
    column11_phone = models.CharField(max_length=10)
    column12_category = models.CharField(max_length=255, blank=True, null=True)
    visited  = models.BooleanField(default=False)
    place_id = models.CharField(max_length=255, blank=True, null=True)

    

    
    
    



    

gmap/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import UploadedFile
from django.contrib.auth.forms import *


class FileUploadForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ['file']

    def clean_file(self):
        file = self.cleaned_data.get('file')
        if file:
            allowed_extensions = ['.csv', '.xls', '.xlsx']
            if not any(file.name.endswith(ext) for ext in allowed_extensions):
                raise ValidationError('Invalid file type. Please upload a CSV or Excel file.')
            
        return file
    

gmap/views.py
from django.shortcuts import render, redirect,HttpResponse
from django.http import JsonResponse
from .forms import *
import pandas as pd
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib import messages
from .models import uploadedData
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt,csrf_protect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.hashers import make_password
import googlemaps
from django.conf import settings


gmaps = googlemaps.Client(key=settings.GOOGLE_API_KEY)

@login_required
def upload_file(request):

    if request.method == 'POST':

        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            
            uploaded_file = form.save(commit=False)
            uploaded_file.save()
            
            handle_uploaded_file(request.FILES['file'])
            
            return redirect('home')
            
    else:
        form = FileUploadForm()
    return render(request, 'gmap/upload.html', {'form': form})


@csrf_exempt
def handle_uploaded_file(file):
    
    if file.name.endswith('.csv'):
        df = pd.read_csv(file)
        
    elif file.name.endswith(('.xls', '.xlsx')):
        
        df = pd.read_excel(file)
        
    instances = []

        
    for index, row in df.iterrows():
        
        full_address = f"{row['address']},{row['city']},{row['state']},{row['country']} {row['zipcode']}"
         
        result = gmaps.geocode(full_address)
        
     
        if result:
            
            location = result[0]['geometry']['location']
            latitude = location['lat']
            longitude = location['lng']
            place_id = result[0]['place_id']
            
        else:
           
            latitude = None
            longitude = None
            place_id = None

        instance = uploadedData(
            
            column1_name=row['name'],
            column2_address=row['address'],           
            column3_latitude=latitude,
            column4_longitude=longitude,
            column5_city=row['city'],
            column6_district=row['district'],
            column7_state=row['state'],
            column8_country=row['country'],
            column9_zipcode=row['zipcode'],
            column10_email=row['email'], 
            column11_phone=row['phone'],
            column12_category=row['category'],
            place_id = place_id         
        )

        instances.append(instance)
        

    uploadedData.objects.bulk_create(instances)
    
    
    
    
    


@csrf_protect
def signup(request):
    
    if request.method == 'POST':
        
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        password = request.POST['password']
        password2 = request.POST['password2']
        email = request.POST['email']

        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username Taken')
                return redirect('signup')
            else:
                user = User.objects.create_user(username=username,first_name=first_name,last_name=last_name,password=password, email=email)
                user.save()
                user_login = authenticate(username=username, password=password)
                if user_login:
                    login(request, user_login)
                return render(request,'gmap/home.html',{'name': username})
        else:
            messages.info(request, 'Passwords do not match')
            return redirect('signup')
    else:
        return render(request, 'gmap/signup.html')

@csrf_protect
def signin(request):
    
    if request.method == 'POST':
        
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            
            login(request, user)
            return render(request,'gmap/home.html',{'name': username})
        
        else:
            messages.error(request, 'Invalid credentials')
            return redirect('login')
    else:
        return render(request, 'gmap/signup.html')
    

@login_required
@csrf_exempt
def show_location(request):
    
    try:
        
        uploaded_data = uploadedData.objects.all()
        
        cities = uploadedData.objects.values_list('column5_city', flat=True).distinct()
        districts = uploadedData.objects.values_list('column6_district', flat=True).distinct()
        states = uploadedData.objects.values_list('column7_state', flat=True).distinct()
        catval = uploadedData.objects.values_list('column12_category', flat=True).distinct
               
        context = {
        'uploaded_data': uploaded_data,
        'cities': cities,
        'districts': districts,
        'states': states,
        'catval':catval,
    }
        
        return render(request,'gmap/maps.html',context)
    
    except uploadedData.DoesNotExist:
        
        raise Http404("Location details do not exist")
    
  
@login_required
@csrf_exempt
def show_leads(request): 
    
    if request.method == 'POST':
        row_number = request.POST.get('row_number')
        is_checked = request.POST.get('is_checked') == 'true'

        
        lead = uploadedData.objects.get(pk=row_number)
        lead.visited = is_checked
        lead.save()

        return JsonResponse({'status': 'success'})
    
    leads_list = uploadedData.objects.all()
    paginator = Paginator(leads_list,20)  
    
    page = request.GET.get('page')
    try:
        leads = paginator.page(page)
    except PageNotAnInteger:        
        
        leads = paginator.page(1)
    except EmptyPage:   
        leads = paginator.page(paginator.num_pages)

    return render(request, 'gmap/leads.html', {'leads': leads})


def home(request):
    
    total_leads = uploadedData.objects.count()
    visited_leads = uploadedData.objects.filter(visited='1').count()
    
    return render(request, 'gmap/home.html', {'total_leads': total_leads,'visited_leads':visited_leads})



    
@login_required
def signout(request):
        logout(request)
        return redirect('login')
    

@login_required
def profile(request):
    
    if request.method == 'GET':
        user_data = {            
            'username': request.user.username,
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'email': request.user.email,
        }
        context = {'user_data': user_data}
        return render(request, 'gmap/profile.html', context)
    
    elif request.method == 'POST':
        user = request.user
        new_password = request.POST.get('new_password')
        confirm_password = request.POST.get('confirm_password')
        
        if new_password or confirm_password:
            if new_password == confirm_password:
                user.set_password(new_password)  
                user.save()
                return redirect('profile')
            else:
                return HttpResponse("Old password incorrect", status=400)
            
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.email = request.POST.get('email')
        user.save()
        return redirect('profile')
    
    
    
def forgot(request):
    
    if request.method == 'POST':
        email = request.POST.get("email")
        password = request.POST.get('password')
        password2 = request.POST.get('password2')

        if password == password2:
            user = User.objects.get(email=email)
            user.password = make_password(password)
            user.save()
            update_session_auth_hash(request, user)  
            
            messages.success(request, 'Your password was successfully updated!')
            return redirect('login') 
        
        else:
            messages.error(request, 'Passwords do not match. Please try again.')
    
    return render(request, 'gmap/forgot.html')

    

    

gmap/templates/gmap/forgot.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
   {%load static%}
   <head>
      <meta charset="utf-8">
      <title></title>
      <link rel="stylesheet" href="{% static 'css/forgot.css' %}">
   </head>
   <body>
      <div class="wrapper">
         <div class="title">
            Reset Password
         </div>
         <form method="POST" action="{% url 'forgot' %}">
            {% csrf_token %}
            
            <div class="field">
                <input type="email" name="email" required>
                <label>Email Address</label>
             </div>
            <div class="field">
                <input type="password" name="password" required>
                <label>Enter New Password</label>
            </div>
            <div class="field">
                <input type="password" name="password2"required>
                <label>Confirm Password</label>
            </div>
            <div class="field">
                <input type="submit" value="Reset">
            </div>
            <div class="signup-link">
                <a href="{% url 'login' %}">Back</a>
             </div>
         </form>
      </div>
   </body>
</html>

gmap/templates/gmap/login.html
<!DOCTYPE html>
{%load static%}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="{%static 'css/styles.css'%}">
    <title>signin-signup</title>
</head>

<body>
    <div class="container">
        <div class="signin-signup">

            <form action="" class="sign-in-form" method="post">

                {% csrf_token %}
                
                <h2 class="title">Log In</h2>
                <div class="input-field">
                    <i class="fas fa-user"></i>
                    <input type="text" placeholder="Username" name="username">
                </div>
                <div class="input-field">
                    <i class="fas fa-lock"></i>
                    <input type="password" placeholder="Password" name="password">
                </div>
                <input type="submit" value="Log in" class="btn">
                <div class="pass-link">
                    <a href="{% url 'forgot' %}">Forgot password?</a>
                 </div>


                <p class="account-text">Don't have an account? <a href="#" id="sign-up-btn2">Sign Up</a></p>

            </form>

            <form action="{% url 'signup' %}" class="sign-up-form" method="post">

                {% csrf_token %}

                <h2 class="title">Sign Up</h2>
                <div class="input-field">
                    <i class="fas fa-user-circle"></i>
                    <input type="text" placeholder="Username" name="username">
                </div>
                <div class="input-field">
                    <i class="fa fa-user"></i>
                    <input type="text" placeholder="Firstname" name="first_name">
                </div>
                <div class="input-field">
                    <i class="fa fa-user"></i>
                    <input type="text" placeholder="Lastname" name="last_name">
                </div>
                <div class="input-field">
                    <i class="fas fa-envelope"></i>
                    <input type="text" placeholder="Email" name="email">
                </div>
                <div class="input-field">
                    <i class="fas fa-lock"></i>
                    <input type="password" placeholder="Password" name="password">
                </div>
                <div class="input-field">
                    <i class="fas fa-lock"></i>
                    <input type="password" placeholder="confirm password" name="password2">
                </div>
                <input type="submit" value="Sign up" class="btn">

                <p class="account-text">Already have an account? <a href="#" id="sign-in-btn2">Log In</a></p>

            </form>
        </div>
        <div class="panels-container">
            <div class="panel left-panel">
                <div class="content">
                    <h3>Already a Member?</h3>
                    <p>Please Login</p>
                    <button class="btn" id="sign-in-btn">Log In</button>
                </div>
                <img src="{%static 'image/signin.svg'%}" alt="" class="image">
            </div>

            <div class="panel right-panel">
                <div class="content">
                    <h3>New to This Platform?</h3>
                    <p>Please Signup</p>
                    <button class="btn" id="sign-up-btn">Sign Up</button>
                </div>
                <img src="{%static 'image/signup.svg'%}" alt="" class="image">
            </div>
        </div>
    </div>
    <script src="{%static 'js/app.js'%}"></script>
</body>

</html>

gmap/templates/gmap/profile.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
</head>
<body>
    <div class="container rounded bg-white mt-5">
        <div class="row">
            <div class="col-md-4 border-right">
                <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                    <img class="rounded-circle mt-5" src="{% static 'image/1.jpg' %}" width="90">
                    <span class="font-weight-bold">{{ user_data.username }}</span>
                    <span class="text-black-50">{{ user_data.email }}</span>
                </div>
            </div>
            <div class="col-md-8">
                <div class="p-3 py-5">
                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <div class="d-flex flex-row align-items-center back">
                            <a href="{% url 'home' %}">
                                <i class="fa fa-long-arrow-left mr-1 mb-1"></i>Back to home
                            </a>
                        </div>
                        <h6 class="text-right">Edit Profile</h6>
                    </div>
                    <form method="post" action="{% url 'profile' %}">
                        {% csrf_token %}
                        <div class="row mt-2">
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="first_name" placeholder="First Name" value="{{ user_data.first_name }}">
                            </div>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="last_name" placeholder="Last Name" value="{{ user_data.last_name }}">
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-md-6">
                                <input type="email" class="form-control" name="email" placeholder="Email" value="{{ user_data.email }}">
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-md-6">
                                <input type="password" class="form-control" name="new_password" placeholder="New Password">
                            </div>
                            <div class="col-md-6">
                                <input type="password" class="form-control" name="confirm_password" placeholder="Confirm Password">
                            </div>

                        </div>
                        
                        <div class="mt-5 text-right">
                            <button class="btn btn-primary " type="submit">Save Profile</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

gmap/templates/gmap/upload.html
<!doctype html>
<html lang="en">
{%load static%}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta name="msapplication-tap-highlight" content="no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="description" content="">
    <meta name="msapplication-tap-highlight" content="no">
    <link href="https://demo.dashboardpack.com/architectui-html-free/main.css" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src='https://api.mapbox.com/mapbox-gl-js/v3.1.2/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v3.1.2/mapbox-gl.css' rel='stylesheet' />
    <link rel="stylesheet" href="{%static 'css/map.css'%}">
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script type="text/javascript"
        src="https://demo.dashboardpack.com/architectui-html-free/assets/scripts/main.js"></script>

        <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <script src="{%static 'js/scripts.js'%}"></script>
</head>

<body>
    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        <div class="app-header header-shadow">
            <div class="app-header__logo">
                <div class=""><a href="{% url 'home'%}">
                        ROUTES
                    </a></div>
                <div class="header__pane ml-auto">
                    <div>
                        <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                            data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <div class="app-header__mobile-menu">
                <div>
                    <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
                    </button>
                </div>
            </div>
            <div class="app-header__menu">
                <span>
                    <div class="widget-heading">

                    </div>


                </span>
            </div>
            <div class="app-header__content ">
                <div class="app-header-left">
                    <div class="search-wrapper">

                        <button class="close"></button>
                    </div>

                </div>
                <div class="app-header-right">
                    <div class="header-btn-lg pr-0">
                        <div class="widget-content p-0">
                            <div class="widget-content-wrapper">
                                <div class="widget-content-left  ml-3 header-user-info">
                                    <div class="widget-heading">

                                    </div>

                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="app-main">
            <div class="app-sidebar sidebar-shadow">
                <div class="app-header__logo">
                    <div class="">
                        <div class=""><a href="{% url 'home'%}">
                                ROUTES
                            </a></div>
                    </div>

                </div>
                <div class="app-header__mobile-menu">
                    <div>
                        <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                        <div class=""><a href="{% url 'home'%}">
                                ROUTES
                            </a></div>

                    </div>
                </div>
                <div class="app-header__menu">
                    <span>
                        <button type="button"
                            class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                            <span class="btn-icon-wrapper">
                                <i class="fa fa-ellipsis-v fa-w-6"></i>
                            </span>
                        </button>
                    </span>
                </div>
                <div class="scrollbar-sidebar">
                    <div class="app-sidebar__inner">
                        <ul class="vertical-nav-menu">
                            <li class="app-sidebar__heading">My Dashboard</li>
                            <li>
                                <a href="{% url 'leads'%}">
                                    <i class="fa fa-user">
                                    </i> View Clients
                                </a>
                            </li>


                            <li>
                                <a href="{% url 'map'%}">
                                    <i class="fa fa-street-view">
                                    </i> Maps
                                </a>
                            </li>
                            <li class="app-sidebar__heading">Upload</li>
                            <li>
                                <a href="{% url 'upload' %}">
                                    <i class="fa fa-upload"></i> Upload Excel/CSV files
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="app-main__outer">

                <div class="row">

                    <div class="d-xl-none d-lg-block col-md-6 col-xl-4">
                    </div>
                </div>
                <div class="row">

                    <div class="col-md-12 ">
                        <div class="mb-3 card">
                            <div class="card-header-tab card-header">
                                <div class="card-header-title">
                                    <i class="header-icon lnr-rocket icon-gradient bg-tempting-azure"> </i>
                                    Upload Files
                                </div>
                            </div>                        
                            <div class="tab-content">
                                <div class="tab-pane fade active show" id="tab-eg-55">
                                    <div class="widget-chart p-3">
                                        <div style="height: 600px">
                                            <form method="post" enctype="multipart/form-data">
                                                <div class="frame">
                                                    <div class="center">
                                                        <div class="title">
                                                            <h1>Drop file to upload</h1>
                                                        </div>
                                                        <div class="dropzone">
                                                            <img src="http://100dayscss.com/codepen/upload.svg" class="upload-icon" />
                                                            <label for="id_file" class="upload-input-label">Choose a file</label>
                                                            <input type="file" class="upload-input" id="id_file" name="file" onchange="displayFileName(this)" />
                                                        </div>
                                                        <p id="file-name-display" style="color: green;"></p>
                                                        <p id="warning-message" style="color: red;">{{ form.file.errors }}</p>
                                                        <div class="btn-container">
                                                            {% csrf_token %}
                                                            <button type="submit" class="btn" name="uploadbutton" onclick="return validateForm()">Upload
                                                                file</button>
                                                            <button type="button" class="clearbtn" onclick="clearFileInput()">Clear</button>
                                        
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>

                                            
                                        </div>
                                        <div class="widget-chart-content text-center mt-5">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>